model:
  type: resnet
  name: resnet101
  num_classes: 80
  fine_tuning:
    strategy: none
    num_layers: 0
    unfreeze_every_n_epochs: 0
lora:
  r: 8
  alpha: 16
  targets:
  - layer4.0.conv2
  - layer4.1.conv2
  - layer4.2.conv2
  - layer3.0.conv2
  - layer3.1.conv2
  - layer3.2.conv2
  - layer3.3.conv2
  - layer3.4.conv2
  - layer3.5.conv2
  - layer3.6.conv2
  - layer3.7.conv2
  - layer3.8.conv2
  - layer3.9.conv2
  - layer3.10.conv2
  - layer3.11.conv2
  - layer3.12.conv2
  - layer3.13.conv2
  - layer3.14.conv2
  - layer3.15.conv2
  - layer3.16.conv2
  - layer3.17.conv2
  - layer3.18.conv2
  - layer3.19.conv2
  - layer3.20.conv2
  - layer3.21.conv2
  - layer3.22.conv2
  - layer2.0.conv2
  - layer2.1.conv2
  - layer2.2.conv2
  - layer2.3.conv2
  gradual_unfreeze:
    enabled: false
    schedule: {}
  learning_rate: 0.001
training:
  batch_size: 128
  epochs: 10
  learning_rate: 0.005
  seed: 42
data:
  name: coco
  data_dir: ./data/coco
  image_size: 224
  train_fraction: 1.0
  augmentation: true
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  imbalance:
    enabled: false
    imbalance_factor: 0.2
    use_weighted_loss: false
    oversample: false
optimizer:
  name: adamw
  lr: 0.005
  lora_lr: 0.001
  weight_decay: 0.0001
scheduler:
  name: cosine_annealing_lr
loss:
  name: cross_entropy
early_stopping:
  enabled: true
  patience: 3
  min_delta: 0.0
logging:
  enabled: true
  run_name: exp14_resnet101_lora-targeted_nl3_r8
  experiment_name: Exp14_MSCOCO_Verification
  dagshub_repo_owner: manuel.voit
  dagshub_repo_name: dd2424-project
  log_metrics: true
  log_confusion_matrix: true
  log_artifact: true
  measure_compute_time: false
