model:
  type: "vit"
  name: "swin_t" # Options: swin_t, swin_s, swin_b, swin_v2_t
  num_classes: 37
  fine_tuning:
    strategy: "none"     # "none" (frozen), "simultaneous" (update all), "gradual"
    num_layers: 2                # Layers to unfreeze
    unfreeze_every_n_epochs: 3   # only for gradual
lora:
  r: 8
  alpha: 16
  learning_rate: 0.0001
  # Targets attention Query/Key/Value projections only in stage 3/4
  targets:
    # Stage 3 (Contains 6 Swin blocks)
    - "features.5.0.attn.qkv"
    - "features.5.1.attn.qkv"
    - "features.5.2.attn.qkv"
    - "features.5.3.attn.qkv"
    - "features.5.4.attn.qkv"
    - "features.5.5.attn.qkv"
    
    # Stage 4 (Contains 2 Swin blocks)
    - "features.7.0.attn.qkv"
    - "features.7.1.attn.qkv"
training:
  batch_size: 32
  epochs: 10
  # ViTs usually require a smaller learning rate
  learning_rate: 0.0005
  seed: 42
data:
  name: "oxford_pets"
  data_dir: "./data"
  image_size: 224
  train_fraction: 1.0
  augmentation: true
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  imbalance:
    enabled: false
    imbalance_factor: 0.2
optimizer:
  name: "adamw"
  lr: 0.0005
  lora_lr: 0.0001
  weight_decay: 0.0
scheduler:
  name: "none"
loss:
  name: "cross_entropy"
early_stopping:
  enabled: true
  patience: 3
  min_delta: 0.0
logging:
  enabled: true
  experiment_name: "Transfer_Learning"
  dagshub_repo_owner: "manuel.voit"
  dagshub_repo_name: "dd2424-project"
  log_metrics: true
  log_confusion_matrix: true
  log_artifact: true
