model:
  type: "resnet"
  name: "resnet50" # Options: resnet18, resnet34, resnet50, resnet101
  num_classes: 37
  fine_tuning:
    strategy: "none"     # "none" (frozen), "simultaneous" (update all), "gradual"
    num_layers: 2                # Layers to unfreeze
    unfreeze_every_n_epochs: 3   # only for gradual
lora:
  r: 8
  alpha: 16
  learning_rate: 0.0001
  # Targets only 3x3 convolutions in layer 3/4
  targets:
    # All 6 blocks in layer 3
    - "layer3.0.conv2"
    - "layer3.1.conv2"
    - "layer3.2.conv2"
    - "layer3.3.conv2"
    - "layer3.4.conv2"
    - "layer3.5.conv2"
    
    # All 3 blocks in layer 4
    - "layer4.0.conv2"
    - "layer4.1.conv2"
    - "layer4.2.conv2"
training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  seed: 42
data:
  name: "oxford_pets"
  data_dir: "./data"
  image_size: 224
  train_fraction: 1.0
  augmentation: true
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 4
  imbalance:
    enabled: false
    imbalance_factor: 0.2
optimizer:
  name: "adamw"
  lr: 0.001
  lora_lr: 0.0001
  weight_decay: 0.0
scheduler:
  name: "none"
loss:
  name: "cross_entropy"
early_stopping:
  enabled: true
  patience: 3
  min_delta: 0.0
logging:
  enabled: true
  experiment_name: "Transfer_Learning"
  dagshub_repo_owner: "manuel.voit"
  dagshub_repo_name: "dd2424-project"
  log_metrics: true
  log_confusion_matrix: true
  log_artifact: true
